version: '3.8'

services:
  backend:
    build:
      context: ./backend 
    volumes:
      - ./backend:/app  
    ports:
      - "8000:8000" 
    environment:
      - DEBUG=True
    depends_on:
      - db  
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend  
    volumes:
      - ./Frontend:/invioce-fromtend 
    ports:
      - "3000:3000" 
    networks:
      - app-network

  db:
    image: postgres:13  
    environment:
      POSTGRES_DB: invoice_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
